//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credit
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.charge = new HashSet<charge>();
        }
    
        public int category_no { get; set; }
        public string category_desc { get; set; }
        public string category_code { get; set; }
    
        public virtual ICollection<charge> charge { get; set; }
    }
}
