//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credit
{
    using System;
    using System.Collections.Generic;
    
    public partial class charge
    {
        public int charge_no { get; set; }
        public int member_no { get; set; }
        public int provider_no { get; set; }
        public int category_no { get; set; }
        public System.DateTime charge_dt { get; set; }
        public decimal charge_amt { get; set; }
        public int statement_no { get; set; }
        public string charge_code { get; set; }
    
        public virtual category category { get; set; }
        public virtual member member { get; set; }
        public virtual provider provider { get; set; }
        public virtual statement statement { get; set; }
    }
}
