//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credit
{
    using System;
    using System.Collections.Generic;
    
    public partial class member2
    {
        public int member_no { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string middleinitial { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string state_prov { get; set; }
        public string country { get; set; }
        public string mail_code { get; set; }
        public string phone_no { get; set; }
        public byte[] photograph { get; set; }
        public System.DateTime issue_dt { get; set; }
        public System.DateTime expr_dt { get; set; }
        public int region_no { get; set; }
        public Nullable<int> corp_no { get; set; }
        public Nullable<decimal> prev_balance { get; set; }
        public Nullable<decimal> curr_balance { get; set; }
        public string member_code { get; set; }
    }
}
