//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDbContext : DbContext
    {
        public TestDbContext()
            : base("name=TestDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> category { get; set; }
        public DbSet<charge> charge { get; set; }
        public DbSet<corporation> corporation { get; set; }
        public DbSet<member> member { get; set; }
        public DbSet<member2> member2 { get; set; }
        public DbSet<payment> payment { get; set; }
        public DbSet<provider> provider { get; set; }
        public DbSet<region> region { get; set; }
        public DbSet<statement> statement { get; set; }
        public DbSet<status> status { get; set; }
    }
}
