//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credit
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int payment_no { get; set; }
        public int member_no { get; set; }
        public System.DateTime payment_dt { get; set; }
        public decimal payment_amt { get; set; }
        public Nullable<int> statement_no { get; set; }
        public string payment_code { get; set; }
    
        public virtual member member { get; set; }
    }
}
