//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credit
{
    using System;
    using System.Collections.Generic;
    
    public partial class provider
    {
        public provider()
        {
            this.charge = new HashSet<charge>();
        }
    
        public int provider_no { get; set; }
        public string provider_name { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string state_prov { get; set; }
        public string mail_code { get; set; }
        public string country { get; set; }
        public string phone_no { get; set; }
        public System.DateTime issue_dt { get; set; }
        public System.DateTime expr_dt { get; set; }
        public int region_no { get; set; }
        public string provider_code { get; set; }
    
        public virtual ICollection<charge> charge { get; set; }
        public virtual region region { get; set; }
    }
}
