//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credit
{
    using System;
    using System.Collections.Generic;
    
    public partial class statement
    {
        public statement()
        {
            this.charge = new HashSet<charge>();
        }
    
        public int statement_no { get; set; }
        public int member_no { get; set; }
        public System.DateTime statement_dt { get; set; }
        public System.DateTime due_dt { get; set; }
        public decimal statement_amt { get; set; }
        public string statement_code { get; set; }
    
        public virtual ICollection<charge> charge { get; set; }
        public virtual member member { get; set; }
    }
}
